lint:
  actions_ci: false
  multiqc_config: false
  files_unchanged:
    - assets/analysis_report.Rmd
    - docs/images/nf-core-hgtseq_logo_dark.png
    - docs/images/nf-core-hgtseq_logo_light.png
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Simone Carpanzano, Francesco Lescai
  description: A pipeline to investigate horizontal gene transfer from NGS data
  force: false
  is_nfcore: true
  name: hgtseq
  org: nf-core
  outdir: .
  version: 1.2.0dev
